// ¡ìbwhat's up
recipes.remove(<additions:attc-whatsup>);
mods.avaritia.ExtremeCrafting.addShaped("999999999999", <additions:attc-whatsup> * 1, [[<avaritia:resource:0>, <avaritia:resource:1>, <avaritia:resource:2>, <avaritia:resource:3>, <avaritia:resource:4>, <avaritia:resource:5>, <avaritia:endest_pearl>, <avaritia:ultimate_stew>, <avaritia:cosmic_meatballs>], [<avaritia:extreme_crafting_table>, <avaritia:block_resource:0>, <avaritia:block_resource:2>, <avaritia:neutron_collector>, <avaritia:neutronium_compressor>, <betterbuilderswands:wandunbreakable:14>, <atum:scarab>, <atum:idol_of_labor>, <bountifulbaubles:trinketankhcharm>],[<biomesoplenty:terrestrial_artifact>, <chisel:chisel_hitech>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:1>, <draconicevolution:draconic_block>, <draconicevolution:infused_obsidian>, <draconicadditions:chaos_crystal_stable>, <draconicevolution:crafting_injector:3>, <draconicevolution:chaos_shard:3>],[<draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:0>, <eternalsingularity:eternal_singularity>, <hooked:hook:4>, <iceandfire:dragon_horn>, <iceandfire:dragonsteel_ice_sword>, <itemfilters:missing>, <lootbags:itemlootbag:11>],[<mekanism:basicblock:2>, <mekanism:machineblock:4>, <mekanism:machineblock2:6>, <mekanism:energycube:0>, <projecte:item.pe_philosophers_stone>, <mekanismgenerators:generator:6>, <mekanismgenerators:generator:5>, <mca:engagement_ring_rg>, <mca:rose_gold_block>],[<projectex:final_star>, <projectex:arcane_tablet>, <projecte:item.pe_transmutation_tablet>, <scalinghealth:heartcontainer>, <solarflux:solar_panel_chaotic>, <solarflux:solar_panel_neutronium>, <solarflux:efficiency_upgrade>, <solarflux:capacity_upgrade>, <solarflux:furnace_upgrade>],[<storagedrawers:controller>, <storagedrawers:compdrawers>, <thermaldynamics:duct_0:5>, <thermaldynamics:duct_16:7>, <thermaldynamics:duct_32:7>, <thermalfoundation:upgrade:35>, <tinker_io:smart_output>, <tconstruct:materials:14>, <tconstruct:materials:50>],[<tconevo:material:2>, <waystones:waystone>, <minecraft:diamond_block>, <minecraft:gold_block>, <minecraft:iron_block>, <minecraft:coal_block>, <minecraft:elytra>, <minecraft:beacon>, <avaritia:skullfire_sword>],[<twilightforest:trophy:0>, <twilightforest:trophy:1>, <twilightforest:trophy:2>, <twilightforest:trophy:3>, <twilightforest:trophy:4>, <twilightforest:trophy:5>, <twilightforest:trophy:6>, <twilightforest:trophy:8>, <twilightforest:fiery_ingot>]]);

//no ingot
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);

// ÎÞ¾¡Ö®¶§
recipes.remove(<avaritia:resource:6>);
mods.avaritia.ExtremeCrafting.addShaped("1111111111111", <avaritia:resource:6> * 1, [[null, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, null], [<additions:attc-whatsup>, <additions:attc-whatsup>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <additions:attc-whatsup>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <avaritia:resource:5>, <additions:attc-whatsup>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <additions:attc-whatsup>, <avaritia:resource:5>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <additions:attc-whatsup>, <avaritia:block_resource:0>, <additions:attc-whatsup>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <avaritia:block_resource:0>, <additions:attc-whatsup>, <avaritia:block_resource:0>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <additions:attc-whatsup>, <avaritia:block_resource:0>, <additions:attc-whatsup>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <avaritia:resource:5>, <additions:attc-whatsup>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <additions:attc-whatsup>, <avaritia:resource:5>, <additions:attc-whatsup>],[<additions:attc-whatsup>, <additions:attc-whatsup>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <additions:attc-whatsup>, <additions:attc-whatsup>],[null, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, <additions:attc-whatsup>, null]]);

